---
- name: Install Couchbase
  hosts: all

  tasks:
  - name: "Check OpenSSL Dependency"
    yum:
      name: pkgconfig
      state: latest
  - name: install the Couchbase rpm from a remote repo
    yum:
      name: http://packages.couchbase.com/releases/couchbase-release/couchbase-release-1.0-5-x86_64.rpm
      state: present
  - name: Installing using yum
    yum:
      name: couchbase-server
      state: latest
#  - name: 'JoinCluster'
#    uri:
#      url: 'http://{{ ip_address }}:{{ port }}/node/controller/doJoinCluster'
#      method: POST
#      body: 'hostname={{ couchbase_server }}&user=Administrator&password=Minhduc7b&services=kv,index,n1ql,fts'
#      body_format: json
#      url_username: {{ username }}
#      url_password: {{ password }}
#    register: result
  - name: 'JoinCluster'
    shell: "curl -u {{ username }}:{{ password }} -v -X POST http://{{ ip_address }}:{{ port }}/node/controller/doJoinCluster -d 'hostname={{ couchbase_server }}&user=Administrator&password=Minhduc7b&services=kv,index,n1ql,fts'"
